name: pull_common
description: Dart package for Pull API and shared logic
version: 0.0.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.0-dev.8
  flutter_hooks: ^0.18.4
  hooks_riverpod: ^2.0.0-dev.8
  go_router: ^3.1.0
  test: ^1.21.1
  isar: 2.5.0
  hive: ^2.2.1
  freezed: ^2.1.0+1
  http: ^0.13.4
  json_annotation: ^4.5.0
  swipable_stack: ^1.3.0
  location: ^4.4.0
  flutter_image_compress: ^1.1.0
  flutter_cache_manager: ^3.3.0
  firebase_auth: ^3.4.0
  pinput: ^2.2.12
  intl_phone_field: ^3.1.0
  tuple: ^2.0.0

dev_dependencies:
  build_runner: any
  freezed_annotation: ^2.0.3
  json_serializable: ^6.2.0
  mocktail: ^0.3.0

environment:
  sdk: ">=2.17.1 <3.0.0"

flutter:
  uses-material-design: true
