// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVQTbgCkmLXAVUkvtd7qKzH-5INTI5Ct0',
    appId: '1:469932598682:web:435eb294d641db95bb8623',
    messagingSenderId: '469932598682',
    projectId: 'pull-68ba0',
    authDomain: 'pull-68ba0.firebaseapp.com',
    storageBucket: 'pull-68ba0.appspot.com',
    measurementId: 'G-J66Z8F6XP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC39gItfLCReNCqg9UNzqCCg_wxVO0LuQs',
    appId: '1:469932598682:android:a18b3e5cdcf6750ebb8623',
    messagingSenderId: '469932598682',
    projectId: 'pull-68ba0',
    storageBucket: 'pull-68ba0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTpiH1tZK5r4ssGdMiwZQ-XstKgE4rDI',
    appId: '1:469932598682:ios:8e91d165d6b3cb8dbb8623',
    messagingSenderId: '469932598682',
    projectId: 'pull-68ba0',
    storageBucket: 'pull-68ba0.appspot.com',
    androidClientId: '469932598682-u02mq1arrai09ikd2thngths2fci2s23.apps.googleusercontent.com',
    iosClientId: '469932598682-e205omf1asdmcauoetr5gf2t44e9mtmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.pullFlutter',
  );
}
